server:
  port: 8878
spring:
  application:
    name: smaato-rest-service
logging:
  level:
    root: info
smaato:
  application:
    single-instance: true
    redis:
      hostname: localhost
      port:   6379
